In [1]:
from dataset import amls_dataset

In [2]:
import csv
import numpy as np
import logging
import pathlib
import os
import time
import torch
from torch import nn, optim
from torch.utils.data import Dataset,DataLoader
from torchvision import models
from PIL import Image
from matplotlib import pyplot as plt

In [3]:
train_datapath = pathlib.Path(r'D:\UCL_codes\0135\data\DIV2K_valid_LR_bicubic')
train_dataset = amls_dataset(train_datapath, "training")

In [15]:
for i in range(800):
    img_lr, img_hr = train_dataset.__getitem__(i)
    if img_hr.shape[1]!=img_hr.shape[2] or img_hr.shape[1]!=510:
        print(i, img_lr.shape,img_hr.shape)

In [5]:
img_lr.shape

torch.Size([1, 255, 255])

In [6]:
img_hr.shape

torch.Size([1, 510, 510])

In [5]:
train_dataset.dataset_list[:10]

[[801,
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X8/0801x8.png'),
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X4/0801x4.png'),
  [255, 169],
  [510, 339]],
 [802,
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X8/0802x8.png'),
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X4/0802x4.png'),
  [255, 169],
  [510, 339]],
 [803,
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X8/0803x8.png'),
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X4/0803x4.png'),
  [255, 192],
  [510, 384]],
 [804,
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X8/0804x8.png'),
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X4/0804x4.png'),
  [255, 150],
  [510, 300]],
 [805,
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X8/0805x8.png'),
  WindowsPath('D:/UCL_codes/0135/data/DIV2K_valid_LR_bicubic/X4/0805x4.png'),
  [255, 192],
  [510, 384]],
 [806,
  WindowsPath('D:/UCL_codes/0135/

In [4]:
x = torch.randn(3, 3)
x

tensor([[ 1.0486,  0.7654,  0.9188],
        [-0.2678, -1.2490,  1.0301],
        [ 0.8327,  1.8991, -0.0349]])

In [5]:
torch.chunk(x, 3, dim=0)

(tensor([[1.0486, 0.7654, 0.9188]]),
 tensor([[-0.2678, -1.2490,  1.0301]]),
 tensor([[ 0.8327,  1.8991, -0.0349]]))

In [7]:
for i in x:
    print(i)

tensor([1.0486, 0.7654, 0.9188])
tensor([-0.2678, -1.2490,  1.0301])
tensor([ 0.8327,  1.8991, -0.0349])
